Update README.md No attibute value for project
- Current example errors with: `for project in get_projects_response.value: AttributeError: 'list' object has no attribute 'value'`
- Updating to print project names